# Generated by Django 2.0.4 on 2018-05-21 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sport_type', models.CharField(default='plogging', max_length=500)),
                ('team_max_size', models.IntegerField(default=10)),
                ('start_timestamp', models.IntegerField(default=0)),
                ('end_timestamp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('captain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='captain_user', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(to='plogin_server.Team'),
        ),
        migrations.AddField(
            model_name='contest',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='plogin_server.Team'),
        ),
    ]
